# Generated by Django 2.0.7 on 2018-07-31 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('project_name', models.CharField(max_length=300)),
                ('strength', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_type', models.IntegerField(choices=[(0, 'L-in'), (1, 'R&D'), (2, 'R&D external')], default=0)),
                ('contract_type', models.IntegerField(choices=[(0, 'LSA'), (1, 'LA+TT'), (2, 'DA')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'pre-PMB'), (1, 'pipeline'), (2, 'portfolio')], default=1)),
                ('prescription_category', models.IntegerField(choices=[(0, 'OTC'), (1, 'Rx'), (2, 'MD'), (3, 'DS')], default=1)),
                ('pack_size', models.CharField(blank=True, max_length=100, null=True)),
                ('shelf_life', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48)])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
