# Generated by Django 2.0.7 on 2018-09-13 15:05

import django.db.models.deletion
from django.db import migrations, models

import pipeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('group', models.ForeignKey(default=pipeline.models.File.default_group, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='pipeline.FileGroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Project')),
            ],
        ),
    ]
