# Generated by Django 2.0.7 on 2018-08-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cogs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dex',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ebidta',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ebitda_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fiveyear_income',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ip',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ip_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='licence_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='licence_costs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mex',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mfd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='moq',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='npv',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='other_costs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pmb_budget',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='regulatory_costs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Unacceptable'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sku',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_costs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
