# Generated by Django 2.0 on 2018-09-14 14:08

import django.db.models.deletion
import filer.fields.file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='project_file', to='filer.File'),
        ),
    ]
