# Generated by Django 2.0 on 2018-09-28 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dropdowns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('name', models.CharField(max_length=300)),
                ('strength', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.IntegerField(choices=[(0, 'License-in'), (1, 'R&D'), (2, 'R&D external')], default=0)),
                ('contract_type', models.IntegerField(choices=[(0, 'LSA'), (1, 'LA+TT'), (2, 'DA')], default=0)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'pre-PMB'), (2, 'projects'), (3, 'portfolio'), (0, 'terminated')], default=2, null=True)),
                ('prescription_category', models.IntegerField(choices=[(0, 'OTC'), (1, 'Rx'), (2, 'MD'), (3, 'DS')], default=1)),
                ('priority', models.IntegerField(blank=True, choices=[(0, 'tbc'), (1, 'Low'), (2, 'Normal'), (3, 'High')], default=0, null=True)),
                ('pack_size', models.TextField(blank=True)),
                ('shelf_life', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48)], default=0, null=True)),
                ('moq', models.CharField(blank=True, max_length=200)),
                ('sku', models.TextField(blank=True)),
                ('cogs', models.TextField(blank=True)),
                ('pmb_budget', models.FloatField(blank=True, default=None, null=True)),
                ('licence_costs', models.FloatField(blank=True, default=None, null=True)),
                ('licence_comment', models.TextField(blank=True)),
                ('regulatory_costs', models.FloatField(blank=True, default=None, null=True)),
                ('other_costs', models.FloatField(blank=True, default=None, null=True)),
                ('total_costs', models.FloatField(blank=True, default=None, null=True)),
                ('fiveyear_income', models.FloatField(blank=True, default=None, null=True)),
                ('npv', models.FloatField(blank=True, default=None, null=True)),
                ('ebidta', models.FloatField(blank=True, default=None, null=True)),
                ('ebitda_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_type', models.IntegerField(blank=True, choices=[(0, 'Unacceptable'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, null=True)),
                ('risk_comment', models.TextField(blank=True)),
                ('ip', models.DateField(blank=True, null=True)),
                ('dex', models.DateField(blank=True, null=True)),
                ('mex', models.DateField(blank=True, null=True)),
                ('mfd', models.DateField(blank=True, null=True)),
                ('ip_comment', models.TextField(blank=True)),
                ('atc_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowns.AtcClass')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdowns.PharmaForm')),
                ('licensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowns.Licensor')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdowns.Market')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdowns.Molecule')),
                ('pact_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowns.PackType')),
                ('therapeutic_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowns.TherapeuticArea')),
            ],
        ),
    ]
