# Generated by Django 2.1.3 on 2019-02-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pact_type',
            new_name='pack_type',
        ),
    ]
