# Generated by Django 2.0 on 2018-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'pre-PMB'), (2, 'pipeline'), (3, 'portfolio'), (0, 'terminated')], default=2, null=True),
        ),
    ]
