# Generated by Django 2.1.2 on 2018-10-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0003_auto_20181010_0951'),
        ('projects', '0002_project_delivery_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agreement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowns.Agreement'),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowns.RegistrationStrategy'),
        ),
    ]
