# Generated by Django 2.1.2 on 2018-10-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181001_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_costs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='agreement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='agreement_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='agreement_expiry',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='agreement_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='agreement_number_eou',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='artwork_approval',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='artwork_approval_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='automatic_prolongation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='batch_release_site',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dossier_availability',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dossier_availability_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dossier_submission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dossier_submission_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='exclusive_suplies',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='exclusivity_period',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='floor_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='floor_price_currency',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='inventory_level',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_date_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lead_time_commercial',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lead_time_launch',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ma_granted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ma_granted_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='manufacturing_site',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='maq',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='notice_period',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_terms',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pmb_approval',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pmb_approval_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='product_in_dsv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='product_in_dsv_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_start_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prolongation_period',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prototype_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prototype_approved_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reconciliation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reconciliation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_batches_ready',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_batches_ready_current',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rolling_forecast',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status_comment_current',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='supply_period',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='supply_price',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='variation_cost',
            field=models.TextField(blank=True),
        ),
    ]
