# Generated by Django 2.1.2 on 2018-10-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181010_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'draft'), (1, 'pre-PMB'), (2, 'pipeline'), (3, 'portfolio'), (4, 'terminated')], default=0, null=True),
        ),
    ]
