# Generated by Django 2.1.2 on 2018-10-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181005_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='automatic_prolongation',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='exclusive_suplies',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='reconciliation',
            field=models.NullBooleanField(),
        ),
    ]
