# Generated by Django 2.1.2 on 2018-10-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtcClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('type', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'ATC-3 Class',
                'verbose_name_plural': 'ATC-3 Classes',
            },
        ),
        migrations.CreateModel(
            name='FormNFC12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Form NFC12',
                'verbose_name_plural': 'Forms NFC12',
            },
        ),
        migrations.CreateModel(
            name='Licensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Licensor',
                'verbose_name_plural': 'Licensors',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Molecule',
                'verbose_name_plural': 'Molecules',
            },
        ),
        migrations.CreateModel(
            name='OtcAtc2Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('type', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'OTC ATC-2 Class',
                'verbose_name_plural': 'OTC ATC-2 Classes',
            },
        ),
        migrations.CreateModel(
            name='PackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Pack type',
                'verbose_name_plural': 'Pack types',
            },
        ),
        migrations.CreateModel(
            name='PharmaForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Pharmaceutical form',
                'verbose_name_plural': 'Pharmaceutical forms',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categorys',
            },
        ),
        migrations.CreateModel(
            name='TherapeuticArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Therapeutic area',
                'verbose_name_plural': 'Therapeutic areas',
            },
        ),
    ]
