# Generated by Django 2.1.2 on 2018-10-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categorys',
            },
        ),
    ]
