# Generated by Django 2.0.7 on 2018-08-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0002_market'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atcclass',
            options={'verbose_name': 'ATC-3 Class', 'verbose_name_plural': 'ATC-3 Classes'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'Market', 'verbose_name_plural': 'Markets'},
        ),
        migrations.AlterModelOptions(
            name='molecule',
            options={'verbose_name': 'Molecule', 'verbose_name_plural': 'Molecules'},
        ),
        migrations.AlterModelOptions(
            name='packtype',
            options={'verbose_name': 'Pack type', 'verbose_name_plural': 'Pack types'},
        ),
        migrations.AlterModelOptions(
            name='pharmaform',
            options={'verbose_name': 'Pharmaceutical form', 'verbose_name_plural': 'Pharmaceutical forms'},
        ),
        migrations.AlterModelOptions(
            name='therapeuticarea',
            options={'verbose_name': 'Therapeutic area', 'verbose_name_plural': 'Therapeutic areas'},
        ),
    ]
