from django.urls import path

from .views import (AtcClassCreateView, AtcClassDeleteView, AtcClassDetailView,
                    AtcClassListView, AtcClassUpdateView, LicensorCreateView,
                    LicensorDeleteView, LicensorDetailView, LicensorListView,
                    LicensorUpdateView, MarketCreateView, MarketDeleteView,
                    MarketDetailView, MarketListView, MarketUpdateView,
                    MoleculeCreateView, MoleculeDeleteView, MoleculeDetailView,
                    MoleculeListView, MoleculeUpdateView, PackTypeCreateView,
                    PackTypeDeleteView, PackTypeDetailView, PackTypeListView,
                    PackTypeUpdateView, PharmaFormCreateView,
                    PharmaFormDeleteView, PharmaFormDetailView,
                    PharmaFormListView, PharmaFormUpdateView,
                    TherapeuticAreaCreateView, TherapeuticAreaDeleteView,
                    TherapeuticAreaDetailView, TherapeuticAreaListView,
                    TherapeuticAreaUpdateView)

urlpatterns = [
    # AtcClass
    path('atcclass/', AtcClassListView.as_view(),
         name='atcclass-list'),
    path('atcclass/<int:pk>/', AtcClassDetailView.as_view(),
         name='atcclass-detail'),
    path('atcclass/create/', AtcClassCreateView.as_view(),
         name='atcclass-create'),
    path('atcclass/<int:pk>/update/', AtcClassUpdateView.as_view(),
         name='atcclass-update'),
    path('atcclass/<int:pk>/delete/', AtcClassDeleteView.as_view(),
         name='atcclass-delete'),
    # licensor
    path('licensor/', LicensorListView.as_view(),
         name='licensor-list'),
    path('licensor/<int:pk>/', LicensorDetailView.as_view(),
         name='licensor-detail'),
    path('licensor/create/', LicensorCreateView.as_view(),
         name='licensor-create'),
    path('licensor/<int:pk>/update/', LicensorUpdateView.as_view(),
         name='licensor-update'),
    path('licensor/<int:pk>/delete/', LicensorDeleteView.as_view(),
         name='licensor-delete'),
    # Market
    path('market/', MarketListView.as_view(),
         name='market-list'),
    path('market/<int:pk>/', MarketDetailView.as_view(),
         name='market-detail'),
    path('market/create/', MarketCreateView.as_view(),
         name='market-create'),
    path('market/<int:pk>/update/', MarketUpdateView.as_view(),
         name='market-update'),
    path('market/<int:pk>/delete/', MarketDeleteView.as_view(),
         name='market-delete'),
    # molecule
    path('molecule/', MoleculeListView.as_view(), name='molecule-list'),
    path('molecule/<int:pk>/', MoleculeDetailView.as_view(),
         name='molecule-detail'),
    path('molecule/create/', MoleculeCreateView.as_view(),
         name='molecule-create'),
    path('molecule/<int:pk>/update/', MoleculeUpdateView.as_view(),
         name='molecule-update'),
    path('molecule/<int:pk>/delete/', MoleculeDeleteView.as_view(),
         name='molecule-delete'),
    # PackType
    path('packtype/', PackTypeListView.as_view(),
         name='packtype-list'),
    path('packtype/<int:pk>/', PackTypeDetailView.as_view(),
         name='packtype-detail'),
    path('packtype/create/', PackTypeCreateView.as_view(),
         name='packtype-create'),
    path('packtype/<int:pk>/update/', PackTypeUpdateView.as_view(),
         name='packtype-update'),
    path('packtype/<int:pk>/delete/', PackTypeDeleteView.as_view(),
         name='packtype-delete'),
    # pharmaform
    path('pharmaform/', PharmaFormListView.as_view(), name='pharmaform-list'),
    path('pharmaform/<int:pk>/', PharmaFormDetailView.as_view(),
         name='pharmaform-detail'),
    path('pharmaform/create/', PharmaFormCreateView.as_view(),
         name='pharmaform-create'),
    path('pharmaform/<int:pk>/update/', PharmaFormUpdateView.as_view(),
         name='pharmaform-update'),
    path('pharmaform/<int:pk>/delete/', PharmaFormDeleteView.as_view(),
         name='pharmaform-delete'),
    # TherapeuticArea
    path('therapeuticarea/', TherapeuticAreaListView.as_view(),
         name='therapeuticarea-list'),
    path('therapeuticarea/<int:pk>/', TherapeuticAreaDetailView.as_view(),
         name='therapeuticarea-detail'),
    path('therapeuticarea/create/', TherapeuticAreaCreateView.as_view(),
         name='therapeuticarea-create'),
    path('therapeuticarea/<int:pk>/update/', TherapeuticAreaUpdateView.as_view(),
         name='therapeuticarea-update'),
    path('therapeuticarea/<int:pk>/delete/', TherapeuticAreaDeleteView.as_view(),
         name='therapeuticarea-delete'),

]
